apiVersion: v1
kind: ConfigMap
metadata:
  name: sre-rag-config
  namespace: sre-exporters
data:
  CLUSTER_ID: "REPLACE_ME"
  S3_ENDPOINT: "https://s3.regru.cloud"
  S3_BUCKET: "sre-rag"
  S3_REGION: "us-east-1"
  S3_VERIFY_SSL: "false"
