apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spokes-k8sgpt-scanner
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/agud97/sre-rag.git
        revision: HEAD
        files:
          - path: clusters/spokes/*.yaml
  template:
    metadata:
      name: '{{ .name }}-k8sgpt-scanner'
    spec:
      project: default
      source:
        repoURL: https://github.com/agud97/sre-rag.git
        targetRevision: HEAD
        path: base/k8sgpt-scanner
      destination:
        name: '{{ .argo_cluster }}'
        namespace: k8sgpt-operator-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
