apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - k8sgpt-exporter.yaml
  # k8sgpt-scanner.yaml is applied manually (different namespace: k8sgpt-operator-system)
