apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubescape-exporter
  namespace: sre-exporters
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: popeye-exporter
  namespace: sre-exporters
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8sgpt-exporter
  namespace: sre-exporters
