authentik:
  secret_key: "authentik-secret-key-change-me"
  postgresql:
    password: "authentik-db-pass-change-me"

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: "17.6.0-debian-12-r4"
  auth:
    username: "authentik"
    password: "authentik-db-pass-change-me"
    database: "authentik"
  primary:
    persistence:
      size: 5Gi
      storageClass: openebs-hostpath

redis:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/redis
    tag: "8.2.1-debian-12-r0"
  auth:
    enabled: false
  master:
    persistence:
      size: 1Gi
      storageClass: openebs-hostpath

server:
  env:
    - name: AUTHENTIK_BOOTSTRAP_PASSWORD
      value: "AuthentikAdmin123!"
    - name: AUTHENTIK_BOOTSTRAP_EMAIL
      value: "admin@runityai.local"
    - name: AUTHENTIK_URL
      value: "http://authentik-server.authentik.svc.cluster.local:9000"
  volumes:
    - name: blueprints-custom
      configMap:
        name: authentik-blueprints
  volumeMounts:
    - name: blueprints-custom
      mountPath: /blueprints/custom

worker:
  volumes:
    - name: blueprints-custom
      configMap:
        name: authentik-blueprints
  volumeMounts:
    - name: blueprints-custom
      mountPath: /blueprints/custom

blueprints:
  configMaps: []
