apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kb-readonly
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "events", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kb-readonly-popeye
subjects:
  - kind: ServiceAccount
    name: popeye
    namespace: kb-system
roleRef:
  kind: ClusterRole
  name: kb-readonly
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kb-readonly-kubescape-exporter
subjects:
  - kind: ServiceAccount
    name: kubescape-exporter
    namespace: kb-system
roleRef:
  kind: ClusterRole
  name: kb-readonly
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kb-readonly-kubevious-exporter
subjects:
  - kind: ServiceAccount
    name: kubevious-exporter
    namespace: kb-system
roleRef:
  kind: ClusterRole
  name: kb-readonly
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kb-readonly-normalizer
subjects:
  - kind: ServiceAccount
    name: normalizer
    namespace: kb-system
roleRef:
  kind: ClusterRole
  name: kb-readonly
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kb-readonly-kubevious-backend
subjects:
  - kind: ServiceAccount
    name: kubevious-backend
    namespace: kb-system
roleRef:
  kind: ClusterRole
  name: kb-readonly
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kb-readonly-kubevious-parser
subjects:
  - kind: ServiceAccount
    name: kubevious-parser
    namespace: kb-system
roleRef:
  kind: ClusterRole
  name: kb-readonly
  apiGroup: rbac.authorization.k8s.io
