apiVersion: v1
kind: ServiceAccount
metadata:
  name: popeye
  namespace: kb-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubescape-exporter
  namespace: kb-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevious-exporter
  namespace: kb-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: normalizer
  namespace: kb-system
