apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.envName }}-env
  description: Test environment ${{ values.envName }}
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/agud97/sre-rag/blob/main/legacy-src/developer-apps/${{ values.envName }}.yaml"
    backstage.io/kubernetes-label-selector: 'environment=${{ values.envName }}'
spec:
  type: environment
  lifecycle: experimental
  owner: platform-team
