apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: kubevious
    repo: https://helm.kubevious.io
    version: 1.2.2
    releaseName: kubevious
    namespace: kb-system
    valuesInline:
      ui:
        service:
          type: ClusterIP
      backend:
        readOnly: true
        livenessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 6
        readinessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 6
resources:
  - kubevious-exporter-cronjob.yaml
patches:
  - target:
      kind: Deployment
      name: kubevious-backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
        value: 30
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe/timeoutSeconds
        value: 2
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe/periodSeconds
        value: 10
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe/failureThreshold
        value: 6
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe/initialDelaySeconds
        value: 10
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe/timeoutSeconds
        value: 2
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe/periodSeconds
        value: 10
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe/failureThreshold
        value: 6
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: "4000"
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 4000
