apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo123-env
  description: Test environment demo123
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/agud97/sre-rag/blob/main/legacy-src/developer-apps/demo123.yaml"
    backstage.io/kubernetes-label-selector: 'environment=demo123'
spec:
  type: service
  lifecycle: experimental
  owner: platform-team
