apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: qa-environment-env
  description: Test environment qa-environment
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/agud97/sre-rag/blob/main/legacy-src/developer-apps/qa-environment.yaml"
    backstage.io/kubernetes-label-selector: 'environment=qa'
spec:
  type: service
  lifecycle: experimental
  owner: platform-team
