apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tim-dev-env
  description: Test environment tim-dev
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/agud97/sre-rag/blob/main/legacy-src/developer-apps/tim-dev.yaml"
    backstage.io/kubernetes-label-selector: 'environment=tim-dev'
spec:
  type: environment
  lifecycle: experimental
  owner: platform-team
