apiVersion: v1
kind: ConfigMap
metadata:
  name: kb-stack-config
  namespace: kb-system
data:
  CLUSTER_ID: prod
  MINIO_ENDPOINT: http://minio.kb-system.svc:9000
  QDRANT_ENDPOINT: http://qdrant.qdrant.svc.cluster.local:6333
  HOLMES_ENDPOINT: http://holmesgpt-holmes.holmesgpt.svc
  KUBEVIOUS_ENDPOINT: http://kubevious-backend-clusterip.kb-system.svc:4000
  EMBEDDING_ENDPOINT: http://embedding-svc.kb-system.svc:7997
  SCHEDULE: "*/30 * * * *"
