apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - cluster-config.yaml
patches:
  - target:
      kind: CronJob
      name: kubescape-exporter
    patch: |-
      - op: replace
        path: /spec/schedule
        value: "*/30 * * * *"
  - target:
      kind: CronJob
      name: popeye
    patch: |-
      - op: replace
        path: /spec/schedule
        value: "*/30 * * * *"
  - target:
      kind: CronJob
      name: kubevious-exporter
    patch: |-
      - op: replace
        path: /spec/schedule
        value: "*/30 * * * *"
  - target:
      kind: CronJob
      name: normalizer
    patch: |-
      - op: replace
        path: /spec/schedule
        value: "*/30 * * * *"
