apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: kubescape-operator
    repo: https://kubescape.github.io/helm-charts/
    version: 1.29.12
    releaseName: kubescape
    namespace: kb-system
    valuesInline:
      clusterName: $(CLUSTER_ID)
      capabilities:
        continuousScan: enable
      operator:
        # Disable secret access by default
        rbac:
          create: true
          pspEnabled: false
resources:
  - kubescape-exporter-cronjob.yaml
